### ISSUE TITLE
ValueError: no path specified with output_path without dir

### ISSUE THREAD

**Issue by tbm** [comwes/mkpdfs-mkdocs-plugin#27]
This works fine:
```
plugins:
    - search
    - mkpdfs:
          output_path: pdf/ledger2beancount.pdf
```

but I want to put the file in the root of the web dir.  With:

```
plugins:
    - search
    - mkpdfs:
          output_path: ledger2beancount.pdf
```

I get:

```
ERROR   -  Error building page 'index.md': no path specified 
Traceback (most recent call last):
  File "/home/tbm/.local/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/home/tbm/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tbm/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tbm/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tbm/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tbm/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tbm/.local/lib/python3.7/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/home/tbm/.local/lib/python3.7/site-packages/mkdocs/commands/build.py", line 295, in build
    _build_page(file.page, config, files, nav, env, dirty)
  File "/home/tbm/.local/lib/python3.7/site-packages/mkdocs/commands/build.py", line 220, in _build_page
    'post_page', output, page=page, config=config
  File "/home/tbm/.local/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/tbm/.local/lib/python3.7/site-packages/mkpdfs_mkdocs/mkpdfs.py", line 58, in on_post_page
    pdf_url = self.generator.add_article(output_content, page, base_url)
  File "/home/tbm/.local/lib/python3.7/site-packages/mkpdfs_mkdocs/generator.py", line 121, in add_article
    return self.get_path_to_pdf(page.file.dest_path)
  File "/home/tbm/.local/lib/python3.7/site-packages/mkpdfs_mkdocs/generator.py", line 178, in get_path_to_pdf
    return os.path.join(os.path.relpath(pdf_split[0], start_dir),
  File "/usr/lib/python3.7/posixpath.py", line 457, in relpath
    raise ValueError("no path specified")
ValueError: no path specified
```

**Comment by tbm** [comment]
A workaround is:

```yaml
          output_path: ./ledger2beancount.pdf
```

but that shouldn't be necessary.
