### ISSUE TITLE
AttributeError: 'Section' object has no attribute 'file'

### ISSUE THREAD

**Issue by asprionj** [comwes/mkpdfs-mkdocs-plugin#4]
I'm getting this error trying to build some (medium-sized) documentation:

```
Traceback (most recent call last):
  File "/home/asprionj/.local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/asprionj/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/asprionj/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/asprionj/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/asprionj/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/asprionj/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/asprionj/.local/lib/python3.6/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/home/asprionj/.local/lib/python3.6/site-packages/mkdocs/commands/build.py", line 298, in build
    config['plugins'].run_event('post_build', config)
  File "/home/asprionj/.local/lib/python3.6/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/asprionj/.local/lib/python3.6/site-packages/mkpdfs_mkdocs/mkpdfs.py", line 64, in on_post_build
    self.generator.write()
  File "/home/asprionj/.local/lib/python3.6/site-packages/mkpdfs_mkdocs/generator.py", line 53, in write
    self.gen_articles()
  File "/home/asprionj/.local/lib/python3.6/site-packages/mkpdfs_mkdocs/generator.py", line 168, in gen_articles
    self.add_tocs()
  File "/home/asprionj/.local/lib/python3.6/site-packages/mkpdfs_mkdocs/generator.py", line 154, in add_tocs
    self._gen_toc_section(n)
  File "/home/asprionj/.local/lib/python3.6/site-packages/mkpdfs_mkdocs/generator.py", line 186, in _gen_toc_section
    stoc = self._gen_toc_for_section(p.file.url, p)
AttributeError: 'Section' object has no attribute 'file'
```

Any idea? When I remove like 80% of the content, it works fine.

**Comment by sebastienlevert** [comment]
I'm getting the same right now. Any findings?

**Comment by stefanteitge-gisa** [comment]
From a quick look at the code:
_gen_toc_section descends into into subsection but assumes sections do only exist at level 1

This should fail:
```
nav:
- Overview: 'index.md'
- 'Milestones':
    - ' Summer:
        - 'Targets': 'summer-targets.md'
```

**Comment by comwes** [comment]
Hi guys! Sorry for answering this late.

I'm gonna work on a fix for a release in few weeks. Currently I'm too busy.

If any of you do have time, feel free to suggest a solution.

KR

**Comment by ryandaugherty** [comment]
Yes please! This would help me too

**Comment by barreeeiroo** [comment]
Hi @comwes, any updates on this?

**Comment by thegrima** [comment]
Hi,

I've also encountered this issue on my test of mkpdfs-mkdocs.

I've managed to pass over the issue by patching generator.py (181) from this :
```
    def _gen_toc_section(self, section):
        for p in section.children:
            if p.is_page and p.meta != None and 'pdf' \
            in p.meta and p.meta['pdf'] == False:
                continue
```

to this :

```
    def _gen_toc_section(self, section):
        for p in section.children:
            if not p.is_page or p.meta != None and 'pdf' \
            in p.meta and p.meta['pdf'] == False:
                continue
```

I guess this will pass theses sections in ToC and a better fix could be implemented, but at least it won't crash.

Hope this helps

**Comment by trogper** [comment]
I have modified the code to create the headings with more and more nested headings (h4, h5, h6), but this requires also changes to css
```
def _gen_toc_section(self, section, level=3):
        for p in section.children:
            if p.is_page and p.meta != None and 'pdf' \
            in p.meta and p.meta['pdf'] == False:
                continue
            if p.is_section:
                level = level + 1
                if level == 7:
                    level = 6
                heading = self.html.new_tag('h' + str(level))
                heading.insert(0, p.title)
                self._toc.append(heading)
                self._gen_toc_section(p, level)
                continue
            stoc = self._gen_toc_for_section(p.file.url, p)
            child = self.html.new_tag('div')
            child.append(stoc)
            self._toc.append(child)
```

the simple option is to always create h3

```
    def _gen_toc_section(self, section):
        for p in section.children:
            if p.is_page and p.meta != None and 'pdf' \
            in p.meta and p.meta['pdf'] == False:
                continue
            if p.is_section:
                h3 = self.html.new_tag('h3')
                h3.insert(0, p.title)
                self._toc.append(h3)
                self._gen_toc_section(p)
                continue
            stoc = self._gen_toc_for_section(p.file.url, p)
            child = self.html.new_tag('div')
            child.append(stoc)
            self._toc.append(child)
```

**Comment by moronic** [comment]
What changes to Css is required?

**Comment by trogper** [comment]
currently only h1, h2 and h3 are styled, h4 to h6 are rendered as default black text, so they would need to be styled also

**Comment by fletort** [comment]
What is waiting for to accept the Open MR ?
I fall also in this bug.....
If it is incomplete, maybe i can help...
