### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Amber1990Zhang** [comwes/mkpdfs-mkdocs-plugin#9]
Some errors happened when I run `mkdocs serve`. The errors as follow:
```
INFO    -  Building documentation...
Unable to revert mtime: /Library/Fonts
INFO    -  Cleaning site directory
WARNING -  A relative path to '../' is included in the 'nav' configuration, which is not found in the documentation files
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkdocs/__main__.py", line 134, in serve_command
    livereload=livereload
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 119, in serve
    config = builder()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkdocs/commands/serve.py", line 114, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 270, in build
    nav = config['plugins'].run_event('nav', nav, config=config, files=files)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkpdfs_mkdocs/mkpdfs.py", line 44, in on_nav
    self.generator.add_nav(nav)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkpdfs_mkdocs/generator.py", line 66, in add_nav
    self.addToOrder(p)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkpdfs_mkdocs/generator.py", line 89, in addToOrder
    for child in page.children:
TypeError: 'NoneType' object is not iterable
```

This is my `yaml` file:

```
site_name: mkdocs versions
repo_url: https://github.com/Amber1990Zhang/versions
repo_name: versions
theme: 'material'
edit_uri: ''
plugins:
  - mkdocs-versioning:
      version: 1.1.0
  # - mkpdfs
nav:
  - Home : 'index.md'
  - Circle: 'circle.md'
  - Triangle: 'triangle.md'
  - Version: '../'
```
Please help, thanks.

**Comment by kruzfuz** [comment]
I'm having the same issue. Have there been any findings on your side in the meantime?

**Comment by kruzfuz** [comment]
If it's of any help to anybody: we realized that the build process fails if mkpdfs cannot find a file where an item in the nav configuration is declared. For you @Amber1990Zhang, that means it is possible that mkpdfs is looking for a file for the "Version" entry in your nav section but cannot find one, and that's why you receive the error message. I hope that helps!

**Comment by comwes** [comment]
Hello @kruzfuz and @Amber1990Zhang,

Currently I'm quite busy at work and will look into this issue as soon as possible.

KR,
Gerry N

**Comment by jwaschkau** [comment]
I think the plugin has a problem with mkdocs>=1.1

I am using mkdocs < 1.1 without a problem

**Comment by igordejanovic** [comment]
I'm having the same issue. Did a quick debugging session and found out that the break occurs if the page is [given in the mkdocs nav configuration is a URL](https://github.com/textX/textX/blob/master/mkdocs.yml#L35). Are links supported in the nav?

**Comment by jwaschkau** [comment]
> 
> 
> I'm having the same issue. Did a quick debugging session and found out that the break occurs if the page is [given in the mkdocs nav configuration is a URL](https://github.com/textX/textX/blob/master/mkdocs.yml#L35). Are links supported in the nav?

I opened a PR ( #26 ) which excludes external links. I think this is the best solution for now as i am not sure how to represent external links in the generated pdf.

**Comment by comwes** [comment]
This should be fixed in the upcoming version
